name: Build & Lint

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.1
        with:
          node-version: "14.x"
      - run: bundle install
      - run: npm install
      - run: npm run lint
